name: smos-report
version: '0.0.0.0'
category: Smos
author: Nick Van den Broeck
maintainer: syd@cs-syd.eu
copyright: ! 'Copyright: (c) 2018 Tom Sydney Kerckhove'
license: AllRightsReserved
homepage: https://github.com/NorfairKing/smos

library:
  source-dirs: src/
  ghc-options: -Wall
  dependencies:
  - base
  - boxes
  - conduit
  - configurator
  - containers
  - filepath
  - optparse-applicative
  - path
  - path-io
  - pretty-show
  - smos-data
  - text
  - time
  - validity
  - validity-path

executables:
  smos-report:
    main: Main.hs
    source-dirs: app
    dependencies:
    - base
    - smos-report
