name: smos-report
version: '0.0.0.0'
category: Smos
author: Tom Sydney Kerckhove
maintainer: syd@cs-syd.eu
copyright: ! 'Copyright: (c) 2018 Tom Sydney Kerckhove'
license: AllRightsReserved
homepage: https://github.com/NorfairKing/smos

library:
  source-dirs: src/
  ghc-options: -Wall
  dependencies:
  - aeson
  - base
  - bytestring
  - conduit
  - containers
  - cursor
  - dhall
  - filepath
  - megaparsec
  - microlens
  - optparse-applicative
  - path
  - path-io
  - pretty-show
  - smos-data
  - text
  - time
  - validity
  - validity-path
  - yaml
