- ignore:
    name: "Use tuple-section"
- ignore:
    name: "Use newtype instead of data"
- ignore:
    name: "Use uncurry"
- ignore:
    name: "Use record patterns"
- ignore:
    name: "Use String"
- ignore:
    name: "Use second"
- ignore:
    name: "Reduce duplication"
- ignore:
    name: "Redundant do"
- ignore:
    name: "Use ++"
- ignore:
    name: "Use ||"
    within:
      - "Smos.Draw.drawEntry"
      - "Smos.Draw.drawEntryCursor"
- ignore:
    name: "Use camelCase"
    within: 
      - "Smos.Report.Archive.HideArchive"
      - "Smos.Scheduler.Commands.Schedule"
- ignore: 
    name: "Use <$>"
    within: 
      - "Smos.Actions.Entry.TodoState.allTodoStatePlainActions"
      - "Smos.Report.Filter.astUnOpP"
- ignore: 
    name: "Avoid lambda"
- ignore: 
    name: "Eta reduce"
- ignore:
    name: "Redundant if"
    within:
      - "Smos.Draw.completedForestNumbersWidget"
      - "Smos.Sync.Client.Contents"
      - "Smos.Sync.Client.isHidden"
      - "Smos.Calendar.Import.RecurrenceRule.Type"
      - "Smos.Calendar.Import.RecurrenceRule.Recurrence.Util"
- ignore:
    name: "Replace case with maybe"
- ignore:
    name: "Use record patterns"
    within:
      - "Smos.Docs.Site.Handler.Keybindings"
      - "Smos.OptParse.Types"
- ignore:
    name: "Hoist not"
    within:
      - "Smos.Calendar.Import.RecurrenceRule"
      - "Smos.Calendar.Import.RecurrenceRule.Gen"
- ignore:
    name: "Use bimap"

- functions:
  # Disallowed functions
  - {name: unsafeDupablePerformIO, within: []}
  - {name: unsafeInterleaveIO, within: []}
  - {name: unsafeFixIO, within: []}
  - {name: nub, within: []}

  # Still to add:
  # - {name: unsafePerformIO, within: []}
  # - {name: fromIntegral, within: []}
