resolver: lts-14.7
packages:
- smos
- smos-data
- smos-data-gen
- smos-cursor
- smos-cursor-gen
- smos-report
- smos-report-gen
- smos-report-cursor
- smos-report-cursor-gen
- smos-query
- smos-single
- smos-convert-org
- smos-archive
- smos-docs-site
- smos-sync-api
- smos-sync-api-gen
- smos-sync-server
- smos-sync-server-gen
- smos-sync-client
- smos-sync-client-gen
extra-deps:
- hakyll-4.13.0.0
- hakyll-sass-0.2.4

- typed-uuid-0.0.0.0@sha256:623b8c37206aa7da887db0e17f590789fd3d602d7a70742b7486fa038981ef90,1272
- genvalidity-typed-uuid-0.0.0.0@sha256:3f3e43d3a2876c977aca262a57c2bc9a6f7411d9a071677ebb8ac01504e99acb,1703

- git: https://github.com/GaloisInc/sqlite.git
  commit: e93ee84000c1d1eedbc23036c4a20ffd07e3145f

- git: https://github.com/NorfairKing/persistent
  commit: 0e3bbb1bd2f5f6383f9eb0407a2416e8b12255ee
  subdirs:
    - persistent
    - persistent-template
    - persistent-sqlite

- git: https://github.com/NorfairKing/mergeful
  commit: 83dc4d8e9415391aa6a1fde37e6af0bbc8bbf4f0
  subdirs:
    - mergeful
    - genvalidity-mergeful
- git: https://github.com/ixmatus/orgmode-parse
  commit: 1bdfbfe8fb7299724a6f6a122a93b2e96dd839f8
- git: https://github.com/NorfairKing/pretty-relative-time.git
  commit: 21b29c9d729ed91a56819f569de6fdc8582d7e3d
- git: https://github.com/NorfairKing/cursor-fuzzy-time.git
  commit: 251f53f7bf12997f2f14ff445fdff818f41f03e8
  subdirs:
    - cursor-fuzzy-time
    - cursor-fuzzy-time-gen
- git: https://github.com/NorfairKing/fuzzy-time.git
  commit: 794427b7d4675910474068c8a0534d07b8eda83d
  subdirs:
    - fuzzy-time
    - fuzzy-time-gen
- git: https://github.com/NorfairKing/cursor-brick.git
  commit: 178d50eac204cdae3d3aeb92c673b18f6245a4cb
  subdirs:
    - cursor-brick
- git: https://github.com/NorfairKing/cursor.git
  commit: 50e180737e7cddd8a405aff1bc94f0202f2d6561
  subdirs:
    - cursor
    - cursor-gen
- git: https://github.com/NorfairKing/validity.git
  commit: 41fc1d893ad1067884217e09e2dceed5b59604b1
  subdirs:
  - genvalidity
  - genvalidity-aeson
  - genvalidity-bytestring
  - genvalidity-containers
  - genvalidity-hspec
  - genvalidity-hspec-aeson
  - genvalidity-hspec-binary
  - genvalidity-hspec-cereal
  - genvalidity-hspec-hashable
  - genvalidity-hspec-optics
  - genvalidity-path
  - genvalidity-property
  - genvalidity-scientific
  - genvalidity-text
  - genvalidity-time
  - genvalidity-unordered-containers
  - genvalidity-uuid
  - genvalidity-vector
  - validity
  - validity-aeson
  - validity-bytestring
  - validity-containers
  - validity-path
  - validity-primitive
  - validity-scientific
  - validity-text
  - validity-time
  - validity-unordered-containers
  - validity-uuid
  - validity-vector
nix:
  path: [ "nixpkgs=https://github.com/NixOS/nixpkgs/archive/e6b93257b0ba070bd12810eeacbe281396c24316.tar.gz" ]
