resolver: lts-14.20
packages:
- smos
- smos-data
- smos-data-gen
- smos-cursor
- smos-cursor-gen
- smos-report
- smos-report-gen
- smos-report-cursor
- smos-report-cursor-gen
- smos-query
- smos-single
- smos-scheduler
- smos-convert-org
- smos-archive
- smos-docs-site
- smos-api
- smos-api-gen
- smos-server
- smos-server-gen
- smos-client
- smos-client-gen
- smos-sync-client
- smos-sync-client-gen
extra-deps:
- hakyll-4.13.0.0
- hakyll-sass-0.2.4

- github: haskell-servant/servant-auth
  commit: 62d3f4b6a7fd7dc38510d4c60982239f94fc1b58
  subdirs:
    - servant-auth-client
    - servant-auth-docs
    - servant-auth-swagger
    - servant-auth-server


- typed-uuid-0.0.0.0@sha256:623b8c37206aa7da887db0e17f590789fd3d602d7a70742b7486fa038981ef90,1272
- genvalidity-typed-uuid-0.0.0.0@sha256:3f3e43d3a2876c977aca262a57c2bc9a6f7411d9a071677ebb8ac01504e99acb,1703
- servant-flatten-0.2@sha256:276896f7c5cdec5b8f8493f6205fded0cc602d050b58fdb09a6d7c85c3bb0837,1234
- Validation-0.2.0@sha256:59c15dd11f509dbea585f590be0e2676de9d764e2812f584d13de86ab939542b,1130


- github: GaloisInc/sqlite
  commit: e93ee84000c1d1eedbc23036c4a20ffd07e3145f

- github: NorfairKing/persistent
  commit: 0e3bbb1bd2f5f6383f9eb0407a2416e8b12255ee
  subdirs:
    - persistent
    - persistent-template
    - persistent-sqlite

- github: NorfairKing/mergeful
  commit: f1c780066a6279cf5b4a4531df0a5ee4eab78c6a
  subdirs:
    - mergeful
    - genvalidity-mergeful
- github: ixmatus/orgmode-parse
  commit: 1bdfbfe8fb7299724a6f6a122a93b2e96dd839f8
- github: NorfairKing/pretty-relative-time
  commit: 8662d4c999d27e6723aa4f4013ecf08b9f92b697
- github: NorfairKing/cursor-fuzzy-time
  commit: 0b1d393a64b0fd357a9ead86c1ef0d6bd2a4c19f
  subdirs:
    - cursor-fuzzy-time
    - cursor-fuzzy-time-gen
- github: NorfairKing/fuzzy-time
  commit: 0c32a1d2e09f1b7421918a845f0b57eceb6752a8
  subdirs:
    - fuzzy-time
    - fuzzy-time-gen
- github: NorfairKing/cursor-brick
  commit: 178d50eac204cdae3d3aeb92c673b18f6245a4cb
  subdirs:
    - cursor-brick
- github: NorfairKing/cursor
  commit: b88cb6f79574fd084f86c322f8e644e10d4cc94e
  subdirs:
    - cursor
    - cursor-gen
- github: NorfairKing/validity
  commit: be40c0a0b0bf6a1d58f4a6a5c6770c4a544c4450
  subdirs:
  - genvalidity
  - genvalidity-aeson
  - genvalidity-bytestring
  - genvalidity-containers
  - genvalidity-criterion
  - genvalidity-hspec
  - genvalidity-hspec-aeson
  - genvalidity-hspec-binary
  - genvalidity-hspec-cereal
  - genvalidity-hspec-hashable
  - genvalidity-hspec-optics
  - genvalidity-path
  - genvalidity-property
  - genvalidity-scientific
  - genvalidity-text
  - genvalidity-time
  - genvalidity-unordered-containers
  - genvalidity-uuid
  - genvalidity-vector
  - validity
  - validity-aeson
  - validity-bytestring
  - validity-containers
  - validity-path
  - validity-primitive
  - validity-scientific
  - validity-text
  - validity-time
  - validity-unordered-containers
  - validity-uuid
  - validity-vector
nix:
  path: [ "nixpkgs=https://github.com/NixOS/nixpkgs/archive/323fe92057bb38475a446ff5e18d3b388c2e4403.tar.gz" ]
  add-gc-roots: true
  packages:
  - zlib
  - haskellPackages.autoexporter
