resolver: lts-12.10
packages:
- smos
- smos-data
- smos-data-gen
- smos-cursor
- smos-cursor-gen
- smos-report
- smos-report-gen
- smos-report-cursor
- smos-report-cursor-gen
- smos-query
- smos-convert-org
extra-deps:
- git: https://github.com/ixmatus/orgmode-parse
  commit: 1bdfbfe8fb7299724a6f6a122a93b2e96dd839f8
- thyme-0.3.5.5
- git: https://github.com/NorfairKing/cursor-fuzzy-time.git
  commit: 13f7585d0b18403b5d78f0c0bbef608d8fad0b40
  subdirs:
    - cursor-fuzzy-time
    - cursor-fuzzy-time-gen
- git: https://github.com/NorfairKing/fuzzy-time.git
  commit: 765afdf9a18566007f26499398a04f3fac6435cd
  subdirs:
    - fuzzy-time
    - fuzzy-time-gen
- git: https://github.com/NorfairKing/cursor.git
  commit: 50fad900ce14c82db4b18eb3767df3d82e1f4939
  subdirs:
    - cursor
    - cursor-gen
- git: https://github.com/NorfairKing/validity.git
  commit: 550327539d84d72ba8be8412025b0074d14c4188
  subdirs:
  - genvalidity
  - genvalidity-aeson
  - genvalidity-bytestring
  - genvalidity-containers
  - genvalidity-hspec
  - genvalidity-hspec-aeson
  - genvalidity-hspec-binary
  - genvalidity-hspec-cereal
  - genvalidity-hspec-hashable
  - genvalidity-hspec-optics
  - genvalidity-path
  - genvalidity-property
  - genvalidity-scientific
  - genvalidity-text
  - genvalidity-time
  - genvalidity-unordered-containers
  - genvalidity-uuid
  - genvalidity-vector
  - validity
  - validity-aeson
  - validity-bytestring
  - validity-containers
  - validity-path
  - validity-primitive
  - validity-scientific
  - validity-text
  - validity-time
  - validity-unordered-containers
  - validity-uuid
  - validity-vector
nix:
  path: [ "nixpkgs=https://github.com/NixOS/nixpkgs/archive/a0248a0b6819153e3fdbc62ce32d7f4e61695c99.tar.gz" ]
