resolver: nightly-2018-07-28
packages:
- smos
- smos-data
- smos-data-gen
- smos-cursor
- smos-cursor-gen
extra-deps:
- git: git@github.com:NorfairKing/cursor.git
  commit: 3206fd7cc1c4dc885358287bf9a4e53aecdc1106
  subdirs:
    - cursor
    - cursor-gen
nix:
  path: [ "nixpkgs=https://github.com/NixOS/nixpkgs/archive/886871538c15681575925a990a3f1b68ed9d5477.tar.gz" ]
