name: smos-report-gen
version: '0.0.0.0'
category: Smos
author: Tom Sydney Kerckhove
maintainer: syd@cs-syd.eu
copyright: ! 'Copyright: (c) 2018 Tom Sydney Kerckhove'
license: AllRightsReserved
homepage: https://github.com/NorfairKing/smos

  
library:
  source-dirs: src/
  ghc-options: -Wall
  dependencies:
  - QuickCheck
  - base >=4.9 && <=5
  - genvalidity
  - genvalidity-path
  - smos-data
  - smos-data-gen
  - smos-report
  - time

tests:
  smos-report-test:
    main: Spec.hs
    source-dirs: test/
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    dependencies:
    - QuickCheck
    - base
    - genvalidity-hspec
    - genvalidity-path
    - hspec
    - smos-data-gen
    - smos-report
    - smos-report-gen
    - time
