work:
  contexts:
    home: '(tag:home or not:tag:office)'
    office: '(tag:office and not:tag:home)'
  time-filter: timewindow
  checks:
    - property:timewindow
  columns:
    - file
    - state
    - header
    - property:timewindow
  sorter: '(reverse:property-as-time:timewindow then file)'

report:
  reports:
    accounting:
      description: 'Anything I need to see during my accounting'
      filter: tag:accounting

scheduler:
  state-file: scheduler-state.yaml
  schedule:
    - description: "Weekly tasks"
      template: templates/weekly.smos.template
      destination: projects/weekly-[ %V | monday ].smos
      schedule: "0 12 * * 7" # Cron schedule: "At 12:00 on Sunday."

calendar:
  sources:
    - name: "Example agenda"
      source: agenda.ics
      destination: calendar.smos
