name: smos-server
version: '0.0.0.0'
category: Smos
author: Tom Sydney Kerckhove
maintainer: syd@cs-syd.eu
copyright: ! 'Copyright: (c) 2019 Tom Sydney Kerckhove'
license: MIT
homepage: https://github.com/NorfairKing/smos

dependencies:
- base

library:
  source-dirs: src/
  ghc-options: -Wall
  dependencies:
  - aeson
  - aeson-pretty
  - base64-bytestring
  - bytestring
  - containers
  - jose
  - mergeful
  - mergeful-persistent
  - monad-logger
  - mtl
  - optparse-applicative
  - path
  - path-io
  - persistent
  - persistent-sqlite
  - persistent-template
  - pretty-show
  - servant
  - servant-auth
  - servant-auth-server
  - servant-server
  - smos-api
  - stm
  - text
  - time
  - typed-uuid
  - uuid
  - wai
  - warp
  - yaml
  - yamlparse-applicative

executables:
  smos-server:
    main: Main.hs
    source-dirs: app
    dependencies:
    - smos-server
