name: smos-server
version: 0.1.1
category: Smos
author: Tom Sydney Kerckhove
maintainer: syd@cs-syd.eu
copyright: ! 'Copyright: (c) 2019-2020 Tom Sydney Kerckhove'
license: MIT
homepage: https://github.com/NorfairKing/smos

dependencies:
- base

library:
  source-dirs: src/
  ghc-options: -Wall
  build-tools: autoexporter
  dependencies:
  - aeson
  - aeson-pretty
  - bytestring
  - conduit
  - containers
  - dirforest
  - envparse
  - filepath
  - jose
  - looper
  - mergeful
  - microlens
  - monad-logger
  - mtl
  - optparse-applicative
  - path
  - path-io
  - persistent
  - persistent-sqlite
  - persistent-template
  - pretty-show
  - semver
  - servant
  - servant-auth-server
  - servant-server
  - smos-api
  - smos-data
  - smos-report
  - template-haskell
  - text
  - time
  - typed-uuid
  - unliftio
  - wai
  - wai-extra
  - warp
  - yaml
  - yamlparse-applicative
  - zip
  - zstd

executables:
  smos-server:
    main: Main.hs
    source-dirs: app
    dependencies:
    - smos-server
