workflow-dir: /home/user
keys:
  reset: true
  file: 
    empty:
      - key: e
        action: startHeaderFromEmptyAndSelectHeader
      - key: E
        action: startHeaderFromEmptyAndSelectHeader
    entry:
      - key: 
          - a
          - A       
        action: entrySelectHeaderAtEnd
      - key: 
          - i
          - I       
        action: entrySelectHeaderAtStart
      - key: 
          - k
          - Up      
        action: forestMoveUp
      - key: 
          - j
          - Down    
        action: forestMoveDown
      - key: 
          - h
          - Left    
        action: forestMoveLeft
      - key:
          - l
          - Right   
        action: forestMoveRight
      - key: <space>nw  
        action: convDoneAndWaitForResponse
      - key: <space>rp  
        action: convRepinged
      - key: EnterEnter 
        action: entrySelectContents
      - key: pi         
        action: entrySelectProperties
      - key: gi         
        action: entrySelectTags
      - key: tc         
        action: entrySetTodoState_CANCELLED
      - key: td         
        action: entrySetTodoState_DONE
      - key: tn         
        action: entrySetTodoState_NEXT
      - key: tr         
        action: entrySetTodoState_READY
      - key: ts         
        action: entrySetTodoState_STARTED
      - key: tt         
        action: entrySetTodoState_TODO
      - key: tw         
        action: entrySetTodoState_WAITING
      - key: t<space>   
        action: entryUnsetTodoState
      - key: co         
        action: forestClockOutEverywhereInAllFiles
      - key: ci         
        action: forestClockOutEverywhereInAllFilesAndClockInHere
      - key: d          
        action: forestDeleteCurrentEntry
      - key: D          
        action: forestDeleteCurrentSubTree
      - key: w, M-l     
        action: forestDemoteEntry
      - key: M-L        
        action: forestDemoteSubTree
      - key: e          
        action: forestInsertEntryAfterAndSelectHeader
      - key: E          
        action: forestInsertEntryBelowAndSelectHeader
      - key: gg         
        action: forestMoveToFirst
      - key: G          
        action: forestMoveToLast
      - key: M-h        
        action: forestPromoteEntry
      - key: M-H        
        action: forestPromoteSubTree
      - key: M-j, M-J   
        action: forestSwapDown
      - key: M-k, M-K   
        action: forestSwapUp
      - key: <tab>      
        action: forestToggleCollapse
      - key: M-<tab>    
        action: forestToggleCollapseRecursively
      - key: S-<tab>    
        action: forestToggleHideEntireEntry
      - key: Del        
        action: helpDelete
      - key: Down, j    
        action: helpDown
      - key: End, G     
        action: helpEnd
      - key: <any char> 
        action: helpInsert
      - key: BS         
        action: helpRemove
      - key: Home, gg   
        action: helpStart
      - key: Up, k      
        action: helpUp
      - key: pc         
        action: propertiesEditProperty_client
      - key: pe         
        action: propertiesEditProperty_effort
      - key: rn         
        action: reportNextActions
      - key: w          
        action: saveFile
      - key: Esc, q     
        action: selectEditor
      - key: ?, M-?     
        action: selectHelp
      - key: q          
        action: stop
      - key: Tc         
        action: subtreeSetTodoState_CANCELLED
      - key: Td         
        action: subtreeSetTodoState_DONE
      - key: Tn         
        action: subtreeSetTodoState_NEXT
      - key: Tr         
        action: subtreeSetTodoState_READY
      - key: Ts         
        action: subtreeSetTodoState_STARTED
    header: []
    contents: []
    timestamps: []
    properties: []
    state: []
    tags: []
    logbook: []
    any: []
  reports:
    next-action: []
  help:
    - key: 
        - Up
        - k
      action: helpUp
    - key: 
       - Down
       - j
      action: helpDown
    - key: 
       - Home
       - gg
      action: helpStart
    - key: 
       - End
       - G
      action: helpEnd
    - key: char
      action: helpInsert
    - key: Del
      action: helpDelete
    - key: BS
      action: helpRemove
    - key: rn
      action: reportNextActions
    - key: Esc
      action: selectEditor
    - key:
        - '?'
        - M-?
      action: selectHelp
    - key: 
        - q
        - Esc
      action: stop
    - key: M-Enter
      action: toggleDebug
    - key: u
      action: undo
