name: smos
version: '0.0.0.0'
category: Smos
author: Tom Sydney Kerckhove
maintainer: syd@cs-syd.eu
copyright: ! 'Copyright: (c) 2018 Tom Sydney Kerckhove'
license: AllRightsReserved
homepage: https://github.com/NorfairKing/smos

library:
  source-dirs: src/
  ghc-options: -Wall
  dependencies:
  - base
  - brick
  - bytestring
  - containers
  - contravariant
  - cursor
  - megaparsec
  - microlens
  - mtl
  - optparse-applicative
  - path
  - path-io
  - pretty-show
  - process
  - safe
  - smos-cursor
  - smos-data
  - text
  - time
  - unordered-containers
  - validity
  - validity-containers
  - validity-text
  - validity-time
  - validity-unordered-containers
  - vty
  - yaml

executables:
  smos:
    main: Main.hs
    source-dirs: app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - base
    - smos

tests:
  smos-test:
    main: Spec.hs
    source-dirs: test/
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    dependencies:
    - QuickCheck
    - base
    - brick
    - cursor
    - cursor-gen
    - genvalidity
    - genvalidity-containers
    - genvalidity-hspec
    - genvalidity-hspec-aeson
    - genvalidity-text
    - genvalidity-time
    - genvalidity-unordered-containers
    - hspec
    - path
    - path-io
    - smos
    - smos-data
    - smos-data-gen
    - text
