name: smos-cursor
version: 0.2.1
github: "NorfairKing/smos"
author: "Tom Sydney Kerckhove"
maintainer: "syd@cs-syd.eu"
copyright: "Copyright: (c) 2018-2020 Tom Sydney Kerckhove"

library:
  source-dirs: src
  dependencies:
  - base
  - containers
  - cursor
  - cursor-dirforest
  - cursor-fuzzy-time
  - deepseq
  - dirforest
  - exceptions
  - filelock
  - fuzzy-time
  - microlens
  - path
  - path-io
  - resourcet
  - smos-archive
  - smos-data
  - text
  - time
  - validity
  - validity-time
