name: smos-server-gen
version: 0.1.0
category: Smos
author: Tom Sydney Kerckhove
maintainer: syd@cs-syd.eu
copyright: ! 'Copyright: (c) 2019-2020 Tom Sydney Kerckhove'
license: MIT
homepage: https://github.com/NorfairKing/smos

dependencies:
- base

library:
  source-dirs: src/
  ghc-options: -Wall
  dependencies:
  - QuickCheck
  - bytestring
  - containers
  - dirforest
  - genvalidity
  - genvalidity-bytestring
  - genvalidity-containers
  - genvalidity-path
  - http-client
  - http-types
  - mergeful
  - microlens
  - monad-logger
  - path
  - path-io
  - persistent-sqlite
  - resource-pool
  - servant-auth-client
  - servant-auth-server
  - servant-client
  - smos-api-gen
  - smos-client
  - smos-client-gen
  - smos-data
  - smos-data-gen
  - smos-report-gen
  - smos-server
  - smos-sync-client
  - stm
  - sydtest
  - sydtest-persistent-sqlite
  - sydtest-servant
  - sydtest-wai
  - text
  - uuid
  - wai
  - warp

tests:
  smos-server-test:
    main: Spec.hs
    source-dirs: test/
    build-tools: sydtest-discover
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    dependencies:
    - QuickCheck
    - containers
    - genvalidity
    - genvalidity-sydtest
    - genvalidity-sydtest-aeson
    - http-types
    - mergeful
    - path
    - path-io
    - persistent-sqlite
    - pretty-show
    - resource-pool
    - servant-client
    - smos-client
    - smos-client-gen
    - smos-data-gen
    - smos-report
    - smos-server
    - smos-server-gen
    - sydtest
    - sydtest-servant
