name: smos-docs-site
version: 0.0.0.0
github: "NorfairKing/smos"
license: MIT
author: "Tom Sydney Kerckhove"
maintainer: "syd@cs-syd.eu"
copyright: "2018-2019 Tom Sydney Kerckhove"


library:
  source-dirs: src
  dependencies:
  - base >= 4.7 && < 5
  - hakyll
  - hakyll-sass
  - smos
  - text
  - directory

executables:
  smos-docs-site:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - base >= 4.7 && < 5
    - smos-docs-site
