name: smos-calendar-import
version: '0.0.0.0'
category: Smos
author: Tom Sydney Kerckhove
maintainer: syd@cs-syd.eu
copyright: ! 'Copyright: (c) 2020 Tom Sydney Kerckhove'
license: MIT
homepage: https://github.com/NorfairKing/smos

dependencies:
- base

library:
  source-dirs: src/
  ghc-options: -Wall
  dependencies:
    - aeson
    - containers
    - data-default
    - envparse
    - fuzzy-time
    - http-client
    - http-client-tls
    - iCalendar
    - microlens
    - mtl
    - network-uri
    - optparse-applicative
    - path
    - path-io
    - pretty-show
    - smos-data
    - smos-report
    - text
    - time
    - validity
    - validity-text
    - yaml
    - yamlparse-applicative

executables:
  smos-calendar-import:
    main: Main.hs
    source-dirs: app
    dependencies:
    - smos-calendar-import

tests:
  smos-calendar-import-test:
    main: Spec.hs
    source-dirs: test
    build-tools: hspec-discover
    dependencies:
    - QuickCheck
    - bytestring
    - containers
    - data-default
    - genvalidity
    - genvalidity-hspec
    - genvalidity-hspec-aeson
    - genvalidity-text
    - hspec
    - iCalendar
    - mtl
    - path
    - path-io
    - pretty-show
    - smos-calendar-import
    - smos-data
    - smos-data-gen
    - text
    - time
    - yaml
    - yamlparse-applicative
