name: smos-cursor-gen
version: 0.1.0
github: "NorfairKing/smos"
author: "Tom Sydney Kerckhove"
maintainer: "sydcs-syd.eu"
copyright: "Copyright: (c) 2018-2020 Tom Sydney Kerckhove"

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  dependencies:
  - QuickCheck
  - base
  - cursor
  - cursor-dirforest
  - cursor-dirforest-gen
  - cursor-fuzzy-time
  - cursor-fuzzy-time-gen
  - cursor-gen
  - fuzzy-time
  - fuzzy-time-gen
  - genvalidity
  - genvalidity-path
  - genvalidity-text
  - genvalidity-time
  - smos-cursor
  - smos-data
  - smos-data-gen

tests:
  smos-cursor-test:
    main: Main.hs
    source-dirs: test
    build-tools: hspec-discover
    # ghc-options:
    # - -threaded
    # - -rtsopts
    # - -with-rtsopts=-N
    dependencies:
    - QuickCheck
    - bytestring
    - cursor
    - cursor-dirforest
    - cursor-fuzzy-time
    - cursor-fuzzy-time-gen
    - cursor-gen
    - dirforest
    - genvalidity-hspec
    - genvalidity-hspec-optics
    - genvalidity-path
    - hspec
    - hspec-core
    - path
    - path-io
    - pretty-show
    - resourcet
    - smos-cursor
    - smos-cursor-gen
    - smos-data
    - smos-data-gen

benchmarks:
  smos-cursor-bench:
    main: Bench.hs
    source-dirs: bench
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - criterion
    - cursor
    - cursor-fuzzy-time
    - cursor-fuzzy-time-gen
    - genvalidity-criterion
    - smos-cursor
    - smos-cursor-gen
    - smos-data
    - smos-data-gen
