name:                smos-cursor-gen
version:             0.0.0.0
github:              "NorfairKing/smos"
author:              "Tom Sydney Kerckhove"
maintainer:          "sydcs-syd.eu"
copyright:           "Copyright: (c) 2018 Tom Sydney Kerckhove"

extra-source-files:
- README.md

description:         Please see the README on GitHub at <https://github.com/NorfairKing/smos#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  dependencies:
  - QuickCheck
  - base
  - cursor
  - cursor-gen
  - genvalidity
  - genvalidity-time
  - smos-cursor
  - smos-data
  - smos-data-gen

tests:
  smos-cursor-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hspec
    - smos-data
    - smos-data-gen
    - smos-cursor
    - smos-cursor-gen
    - genvalidity-hspec
    - genvalidity-hspec-optics
