name: "Nix Build"
on:
  pull_request:
  push:
    branches:
      - development
      - master

jobs:
  hooks:
    name: Pre-commit hooks
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: cachix/install-nix-action@v11
    - uses: cachix/cachix-action@ffed6b919f842f223dbee6fde9d3d1cdf23a118e
      with:
        name: smos
        extraPullNames: cachix,iohk,validity,dirforest,cursor,cursor-dirforest,mergeful,yamlparse
        signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
    - run: nix run -f nix/build-uncached.nix -c nix-build-uncached static.nix


  dynamic:
    name: Normal build: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
    steps:
    - uses: actions/checkout@v2
    - uses: cachix/install-nix-action@v11
    - name: free disk space
      run: |
        if [[ "${{matrix.os}}" == "ubuntu-latest" ]]
        then
          sudo rm -rf /opt
        fi
    - uses: cachix/cachix-action@ffed6b919f842f223dbee6fde9d3d1cdf23a118e
      with:
        name: smos
        extraPullNames: cachix
        signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
    - run: nix run -f nix/build-uncached.nix -c nix-build-uncached default.nix


  static:
    name: Static Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: cachix/install-nix-action@v11
    - name: free disk space
      run: sudo rm -rf /opt
    - uses: cachix/cachix-action@ffed6b919f842f223dbee6fde9d3d1cdf23a118e
      with:
        name: smos
        extraPullNames: cachix,iohk,validity,dirforest,cursor,cursor-dirforest,mergeful,yamlparse
        signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
    - run: nix run -f nix/build-uncached.nix -c nix-build-uncached static.nix
