name: "Nix Build"
on:
  pull_request:
  push:
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: cachix/install-nix-action@v6
    - uses: cachix/cachix-action@v2
      with:
        name: smos
        signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
    - uses: cachix/cachix-action@v2
      with:
        name: smos
        file: nix/release.nix
        signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
