name: "Stack Build"
on:
  pull_request:
  push:
    branches:
      - development
      - master
jobs:
  stack-build:
    name: ${{ matrix.os }} / Stack ${{ matrix.stack }} / GHC ${{ matrix.ghc }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
        stack:
          - 2.1.3
        ghc:
          - 8.6.5
    steps:
      - uses: actions/checkout@v2
        if: github.event.action == 'opened' || github.event.action == 'synchronize' || github.event.ref == 'refs/heads/master' || github.event.ref == 'refs/heads/development'

      - uses: actions/setup-haskell@v1.1
        name: Setup Haskell Stack
        with:
          ghc-version: ${{ matrix.ghc }}
          stack-version: ${{ matrix.stack }}

      - uses: cachix/install-nix-action@v8


      - uses: actions/cache@v1
        name: Cache ~/.stack
        with:
          path: ~/.stack
          key: ${{ runner.os }}-${{ matrix.ghc }}-stack

      - name: Build frontend
        run: |
          cd smos-web-server/front && nix-shell --run "yarn bundle"

      - name: Build autoexporter
        run: |
          stack install --system-ghc autoexporter

      - name: Build smos packages
        run: |
          stack build --system-ghc --test --bench --no-run-tests --no-run-benchmarks --jobs 1 --test-arguments='--seed=42' \
            smos \
            smos-api \
            smos-api-gen \
            smos-archive \
            smos-asciinema \
            smos-calendar-import \
            smos-client \
            smos-client-gen \
            smos-convert-org \
            smos-cursor \
            smos-cursor-gen \
            smos-data \
            smos-data-gen \
            smos-query \
            smos-report \
            smos-report-cursor \
            smos-report-cursor-gen \
            smos-report-gen \
            smos-scheduler \
            smos-server \
            smos-server-gen \
            smos-single \
            smos-sync-client \
            smos-sync-client-gen \
            smos-web-server
