name: smos-sync-client-gen
version: '0.0.0.0'
category: Smos
author: Tom Sydney Kerckhove
maintainer: syd@cs-syd.eu
copyright: ! 'Copyright: (c) 2019 Tom Sydney Kerckhove'
license: MIT
homepage: https://github.com/NorfairKing/smos

dependencies:
- base

library:
  source-dirs: src/
  ghc-options: -Wall
  dependencies:
  - QuickCheck
  - bytestring
  - containers
  - genvalidity
  - genvalidity-hspec
  - hspec
  - hspec-core
  - http-client
  - mergeful
  - path
  - path-io
  - servant-client
  - smos-sync-api-gen
  - smos-sync-client
  - smos-sync-server-gen
  - stm
  - uuid
  - wai
  - warp

tests:
  smos-sync-client-test:
    main: Spec.hs
    source-dirs: test/
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    dependencies:
    - QuickCheck
    - bytestring
    - containers
    - genvalidity
    - genvalidity-hspec
    - genvalidity-hspec-aeson
    - genvalidity-hspec-optics
    - hspec
    - hspec-core
    - mergeful
    - monad-logger
    - path
    - path-io
    - pretty-show
    - servant-client
    - smos-report
    - smos-sync-api
    - smos-sync-client
    - smos-sync-client-gen
    - smos-sync-server
    - smos-sync-server-gen
    - uuid
